CREATE DATABASE YetiCave
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE YetiCave;

CREATE TABLE categories (
id INT AUTO_INCREMENT,
name VARCHAR(64) UNIQUE NOT NULL,

PRIMARY KEY(id)
)ENGINE = InnoDB CHARACTER SET = UTF8;

CREATE INDEX name_categories ON categories(name);

CREATE TABLE users (
id INT AUTO_INCREMENT,
created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
email VARCHAR(30) UNIQUE NOT NULL,
name VARCHAR(20) NOT NULL,
password VARCHAR(60) NOT NULL,
avatar VARCHAR(64),
contact VARCHAR(30) NOT NULL,

PRIMARY KEY(id)
)ENGINE = InnoDB CHARACTER SET = UTF8;

CREATE TABLE lots (
id INT AUTO_INCREMENT,
created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
name VARCHAR(128) NOT NULL,
description TEXT NOT NULL,
picture VARCHAR(128) NOT NULL,
start_price INT UNSIGNED NOT NULL,
date_of_completion DATETIME NOT NULL,
step INT UNSIGNED NOT NULL,

id_author INT NOT NULL,
id_winner INT,
id_categori INT NOT NULL,

PRIMARY KEY(id),
FOREIGN KEY(id_author) REFERENCES users(id),
FOREIGN KEY(id_winner) REFERENCES users(id),
FOREIGN KEY(id_categori) REFERENCES categories(id)
)ENGINE = InnoDB CHARACTER SET = UTF8;

CREATE INDEX name_lot ON lots(name);
CREATE INDEX description ON lots(description(255));

CREATE TABLE bets (
id INT AUTO_INCREMENT,
date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
sum INT UNSIGNED,

id_user INT NOT NULL,
id_lot INT NOT NULL,

PRIMARY KEY(id),
FOREIGN KEY(id_user) REFERENCES users(id),
FOREIGN KEY(id_lot) REFERENCES lots(id)
)ENGINE = InnoDB CHARACTER SET = UTF8;

