CREATE DATABASE YetiCave
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE YetiCave;

CREATE TABLE category (
id INT AUTO_INCREMENT,
name VARCHAR(64) UNIQUE NOT NULL,

PRIMARY KEY(id)
)ENGINE = InnoDB CHARACTER SET = UTF8;

CREATE INDEX name_category ON category(name);

CREATE TABLE user (
id INT AUTO_INCREMENT,
created_date DATETIME NOT NULL,
email VARCHAR(30) UNIQUE NOT NULL,
name VARCHAR(20) NOT NULL,
password VARCHAR(60) NOT NULL,
avatar VARCHAR(64),
contact VARCHAR(30),

PRIMARY KEY(id)
)ENGINE = InnoDB CHARACTER SET = UTF8;

CREATE TABLE lot (
id INT AUTO_INCREMENT,
created_date DATETIME NOT NULL,
name VARCHAR(128) NOT NULL,
description TEXT NOT NULL,
picture VARCHAR(128) NOT NULL,
start_price INT UNSIGNED NOT NULL,
date_of_completion DATETIME NOT NULL,
step INT UNSIGNED NOT NULL,

id_author INT NOT NULL,
id_winner INT,
id_category INT NOT NULL,

PRIMARY KEY(id),
FOREIGN KEY(id_author) REFERENCES user(id),
FOREIGN KEY(id_winner) REFERENCES user(id),
FOREIGN KEY(id_category) REFERENCES category(id)
)ENGINE = InnoDB CHARACTER SET = UTF8;

CREATE INDEX name_lot ON lot(name);
CREATE INDEX description ON lot(description(255));

CREATE TABLE bet (
id INT AUTO_INCREMENT,
date DATETIME,
sum INT UNSIGNED,

id_user INT NOT NULL,
id_lot INT NOT NULL,

PRIMARY KEY(id),
FOREIGN KEY(id_user) REFERENCES user(id),
FOREIGN KEY(id_lot) REFERENCES lot(id)
)ENGINE = InnoDB CHARACTER SET = UTF8;
